services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: "${container_name}"
    restart: unless-stopped
    environment:
      SECRET_KEY: "${SECRET_KEY}"
      ENABLE_CORS: "${ENABLE_CORS}"
      CORS_ALLOW_ORIGINS: "${CORS_ALLOW_ORIGINS}"
      CORS_ALLOW_CREDENTIALS: "${CORS_ALLOW_CREDENTIALS}"
      ENCRYPTION_KEY: "${ENCRYPTION_KEY}"
      DB_HOST: "${DB_HOST}"
      DB_DATABASE: "${DB_DATABASE}"
      DB_USER: "${DB_USER}"
      DB_PASSWORD: "${DB_PASSWORD}"
      DB_PORT: "${DB_PORT}"
      SMTP_HOST: "${SMTP_HOST}"
      SMTP_PORT: "${SMTP_PORT}"
      SMTP_USER: "${SMTP_USER}"
      SMTP_PASSWORD: "${SMTP_PASSWORD}"
    networks:
      - dokploy-network

networks:
  dokploy-network:
    external: true
